-- MySQL Script generated by MySQL Workbench
-- Mon Dec  2 13:51:21 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema American_Friends
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema American_Friends
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `American_Friends` DEFAULT CHARACTER SET utf8 ;
USE `American_Friends` ;

-- -----------------------------------------------------
-- Table `American_Friends`.`Address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `American_Friends`.`Address` ;

CREATE TABLE IF NOT EXISTS `American_Friends`.`Address` (
  `City` VARCHAR(15) NOT NULL,
  `Street` VARCHAR(25) CHARACTER SET 'utf16' NOT NULL,
  `Zip` INT(5) UNSIGNED NULL,
  PRIMARY KEY (`Street`, `City`),
  INDEX `Event_City` (`City` ASC) INVISIBLE,
  INDEX `Event_Street` (`Street` ASC) INVISIBLE,
  INDEX `Student_Street` (`Street` ASC) INVISIBLE,
  INDEX `Student_City` (`City` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `American_Friends`.`Driver`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `American_Friends`.`Driver` ;

CREATE TABLE IF NOT EXISTS `American_Friends`.`Driver` (
  `License#` VARCHAR(10) CHARACTER SET 'ascii' NOT NULL COMMENT 'License plate number of driver',
  `Driver_Name` VARCHAR(25) CHARACTER SET 'utf32' NOT NULL COMMENT 'Name of Driver',
  `Max_Capacity` SMALLINT UNSIGNED NULL DEFAULT 4 COMMENT 'Maximum number of seats available in a car',
  `Event_City` VARCHAR(15) NOT NULL,
  `Event_Street` VARCHAR(25) CHARACTER SET 'utf16' NOT NULL,
  `Gender` BIT NULL COMMENT '0 = female, \n1 = male',
  PRIMARY KEY (`License#`, `Driver_Name`),
  INDEX `E_Street_idx` (`Event_Street` ASC) VISIBLE,
  INDEX `E_City_idx` (`Event_City` ASC) INVISIBLE,
  INDEX `D_Name` (`Driver_Name` ASC) VISIBLE,
  CONSTRAINT `E_Street`
    FOREIGN KEY (`Event_Street`)
    REFERENCES `American_Friends`.`Address` (`Street`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `E_City`
    FOREIGN KEY (`Event_City`)
    REFERENCES `American_Friends`.`Address` (`City`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `American_Friends`.`Student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `American_Friends`.`Student` ;

CREATE TABLE IF NOT EXISTS `American_Friends`.`Student` (
  `Gender` BIT NULL COMMENT 'Student\'s Gender\n0 = female,\n1 = male',
  `Age` TINYINT UNSIGNED NOT NULL,
  `Student_Name` VARCHAR(25) CHARACTER SET 'utf32' NOT NULL COMMENT 'Student\'s Name',
  `Country_of_Origin` VARCHAR(20) NULL,
  `City_Lives_In` VARCHAR(15) NOT NULL,
  `Street_Lives_On` VARCHAR(25) CHARACTER SET 'utf16' NOT NULL,
  `D_Name` VARCHAR(25) CHARACTER SET 'utf32' NOT NULL,
  INDEX `Student_City_idx` (`City_Lives_In` ASC) VISIBLE,
  PRIMARY KEY (`Age`, `Student_Name`),
  INDEX `Age_idx` (`Age` ASC) VISIBLE,
  INDEX `Student_Name` (`Student_Name` ASC) VISIBLE,
  INDEX `D_Name_idx` (`D_Name` ASC) INVISIBLE,
  INDEX `Student_Street_idx` (`Street_Lives_On` ASC) INVISIBLE,
  CONSTRAINT `Student_Street`
    FOREIGN KEY (`Street_Lives_On`)
    REFERENCES `American_Friends`.`Address` (`Street`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Student_City`
    FOREIGN KEY (`City_Lives_In`)
    REFERENCES `American_Friends`.`Address` (`City`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `D_Name`
    FOREIGN KEY (`D_Name`)
    REFERENCES `American_Friends`.`Driver` (`Driver_Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `American_Friends`.`Route`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `American_Friends`.`Route` ;

CREATE TABLE IF NOT EXISTS `American_Friends`.`Route` (
  `Date` DATE NOT NULL,
  `D_Name` VARCHAR(25) CHARACTER SET 'utf32' NOT NULL,
  `Student_Location_City` VARCHAR(15) NOT NULL,
  `Student_Location_Street` VARCHAR(25) CHARACTER SET 'utf16' NOT NULL,
  `Event_Location_City` VARCHAR(15) NOT NULL,
  `Event_Location_Street` VARCHAR(25) CHARACTER SET 'utf16' NOT NULL,
  INDEX `Driver_Name_idx` (`D_Name` ASC) INVISIBLE,
  PRIMARY KEY (`Date`),
  INDEX `Student_City_Location_idx` (`Student_Location_City` ASC) VISIBLE,
  INDEX `Student_Street_Location_idx` (`Student_Location_Street` ASC) VISIBLE,
  INDEX `Event_City_Location_idx` (`Event_Location_City` ASC) VISIBLE,
  INDEX `Event_Street_Location_idx` (`Event_Location_Street` ASC) VISIBLE,
  CONSTRAINT `Driver_Name`
    FOREIGN KEY (`D_Name`)
    REFERENCES `American_Friends`.`Driver` (`Driver_Name`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `Student_City_Location`
    FOREIGN KEY (`Student_Location_City`)
    REFERENCES `American_Friends`.`Address` (`City`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Student_Street_Location`
    FOREIGN KEY (`Student_Location_Street`)
    REFERENCES `American_Friends`.`Address` (`Street`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Event_City_Location`
    FOREIGN KEY (`Event_Location_City`)
    REFERENCES `American_Friends`.`Address` (`City`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Event_Street_Location`
    FOREIGN KEY (`Event_Location_Street`)
    REFERENCES `American_Friends`.`Address` (`Street`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `American_Friends`.`Belongs_To`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `American_Friends`.`Belongs_To` ;

CREATE TABLE IF NOT EXISTS `American_Friends`.`Belongs_To` (
  `Student_Name` VARCHAR(25) CHARACTER SET 'utf32' NOT NULL,
  `Stu_Age` TINYINT UNSIGNED NOT NULL,
  `Route_Date` DATE NOT NULL,
  INDEX `Route_Date_idx` (`Route_Date` ASC) VISIBLE,
  INDEX `Student_Name_idx` (`Student_Name` ASC) INVISIBLE,
  INDEX `Stu_Age_idx` (`Stu_Age` ASC) VISIBLE,
  CONSTRAINT `Route_Date`
    FOREIGN KEY (`Route_Date`)
    REFERENCES `American_Friends`.`Route` (`Date`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `Stu_Name`
    FOREIGN KEY (`Student_Name`)
    REFERENCES `American_Friends`.`Student` (`Student_Name`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `Stu_Age`
    FOREIGN KEY (`Stu_Age`)
    REFERENCES `American_Friends`.`Student` (`Age`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
